[default.extend-words]
# False positives to ignore
eit = "eit"
pn = "pn"
Ome = "Ome"
haa = "haa"
"fo" = "fo"
"ba" = "ba"

# Intentional command typos
lsit = "lsit"
instal = "instal"
intsall = "intsall"
inof = "inof"
ifno = "ifno"
rnu = "rnu"
reqoquery = "reqoquery"
reqoqury = "reqoqury"
whoneds = "whoneds"
uninstal = "uninstal"
creat = "creat"
remov = "remov"
confog = "confog"
activ = "activ"
actiavte = "actiavte"
