name: Bug report
description: Problem using Mamba / Micromamba
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Troubleshooting docs
      description: Please check the [troubleshooting docs](https://mamba.readthedocs.io/en/latest/user_guide/troubleshooting.html) before making a report.
      options:
        - label: "My problem is not solved in the Troubleshooting docs"
          required: true
  - type: input
    id: search
    attributes:
      label: Search tried in issue tracker
      description: Please search for similar issues before making a report.
      placeholder: ...
    validations:
      required: true
  - type: dropdown
    id: conda_reproducible
    attributes:
      label: Tried in Conda?
      description: |
        If possible, please try to reproduce your problem with Conda (without Mamba or Micromamba).
        
        Can you reproduce the problem with Conda?
      options:
        - "Reproducible with Conda"
        - "Not reproducible with Conda"
        - "Didn't try"
        - "Not applicable"
    validations:
      required: true
  - type: textarea
    id: freeform
    attributes:
      label: Describe your issue
    validations:
      required: true
  - type: textarea
    id: mamba_info
    attributes:
      label: mamba info / micromamba info
      description: |
        Please post the output of `mamba info` / `micromamba info`.
        
        Auto-rendered as code, no need for backticks.
      render: shell
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Verbose logs of the problematic command, eg. `mamba install -v ...`.
        
        Auto-rendered as code, no need for backticks.
      render: shell
  - type: textarea
    id: environment_yml
    attributes:
      label: environment.yml
      description: |
        Please post your `environment.yml` file if applicable.
        
        Auto-rendered as code, no need for backticks.
      placeholder: |
        name: ...
        channels: ...
        dependencies: ...
      render: yaml
  - type: textarea
    id: condarc
    attributes:
      label: ~/.condarc
      description: |
        `cat ~/.condarc`
        
        Auto-rendered as code, no need for backticks.
      render: yaml
