{% set version = "0.26.0" %}
{% set build_num = 0 %}

package:
  name: micromamba
  version: {{ version }}

source:
  - git_url: ../
    patches:
      - libmamba.patch

build:
  number: {{ build_num }}
  string: {{ build_num }}
  ignore_run_exports_from:
    - libcurl                  # [unix]
    - libarchive               # [unix]
    - reproc-cpp               # [unix]
    - openssl                  # [unix]
    - spdlog
    - {{ compiler('c') }}      # [linux]
    - {{ compiler('cxx') }}    # [linux]
    - python                   # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [unix]
    - make   # [unix]
    - ninja  # [win]
    - vcpkg  # [win]
    - python  # [win]
    # force a recent curl version for windows
    - curl >=7.75  # [win]
    - zlib  # [win]
  host:
    - cli11 >=2.2,<3
    - cpp-expected
    - nlohmann_json
    - spdlog
    - termcolor-cpp
    - yaml-cpp-static              # [unix]
    # we pin an older curl build for darwin-ssl support
    - libcurl 7.76.1 *_0           # [osx]
    - libcurl-static  7.76.1 *_0   # [osx]
    - libcurl                      # [linux]
    - libcurl-static               # [linux]
    - xz-static          # [unix]
    - libssh2-static     # [unix]
    - libarchive         # [unix]
    - krb5-static        # [unix]
    - libsolv-static     # [unix]
    - openssl            {{ openssl }}  # [unix]
    - libopenssl-static  {{ openssl }}  # [unix]
    - zstd-static        # [unix]
    - libnghttp2-static  # [unix]
    - lz4-c-static       # [unix]
    - reproc-static      # [unix]
    - reproc-cpp         # [unix]
    - reproc-cpp-static  # [unix]
    - winreg             # [win]

test:
  commands:
    - test -f $PREFIX/bin/micromamba                                          # [unix]
    - micromamba --help
    - export TMPDIR="${TMPDIR:-/tmp}"                                         # [unix and not (ppc64le or aarch64)]
    - if [ ! -d "${TMPDIR}" ]; then mkdir -p "${TMPDIR}"; fi                  # [unix and not (ppc64le or aarch64)]
    - stat $TMPDIR                                                            # [unix and not (ppc64le or aarch64)]
    - export MAMBA_ROOT_PREFIX=$TMPDIR/mamba                                  # [unix and not (ppc64le or aarch64)]
    - micromamba create -p $TMPDIR/testenv --override-channels -c conda-forge --yes python=3.9    # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python --version                                    # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python -c 'import ssl'                              # [unix and not (ppc64le or aarch64)]

about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - REPROC_LICENSE.txt
    - TERMCOLOR_CPP_LICENSE.txt
    - SPDLOG_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - mariusvniekerk
    - adriendelsalle
