name: Homebrew toolchain

on:
  workflow_call:

jobs:
  build_homebrew:
    name: Build on homebrew
    runs-on: macos-15

    steps:
      - name: Checkout mamba repository
        uses: actions/checkout@v7

      # Note: cmake already installed from a local Github tap
      # Attempting to install it from homebrew/core creates a conflict without more handling
      - name: Install host and build dependencies
        run: >
          brew install --overwrite
          fmt libarchive libsolv lz4 openssl@3 reproc simdjson xz yaml-cpp zstd
          cli11 nlohmann-json spdlog tl-expected pkgconfig python msgpack

      - name: Configure to build mamba
        run: >
          cmake -S. -Bbuild -DBUILD_LIBMAMBA=ON -DBUILD_MAMBA=ON -DBUILD_LIBMAMBA_SPDLOG=ON -DBUILD_SHARED=ON -DBUILD_STATIC=OFF
          -DLibArchive_ROOT=$(brew --prefix libarchive)

      - name: Build mamba
        run: cmake --build build -j4
