name: conda-build Linux
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  linux-conda-build:
    name: "Linux - conda-build - Python ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: ubuntu-latest
    env:
      CI: True
    strategy:
      fail-fast: true
      matrix:
        CONDA_BUILD_YML:
          - linux_64_
          - linux_aarch64_
          - linux_ppc64le_
    steps:
      - name: Pull image
        run: docker pull condaforge/mambaforge:latest
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - name: Run CI inside of container
        uses: ./.github/actions/conda-build
        with:
          conda_build_yml: ${{ matrix.CONDA_BUILD_YML }}

  macos-conda-build:
    name: "MacOS - conda-build - Python ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: macos-latest
    env:
      CI: True
      CONDA_BUILD_YML: ${{ matrix.CONDA_BUILD_YML }}
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - osx_64_
          - osx_arm64_
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: mamba-org/provision-with-micromamba@main
        with:
          channels: conda-forge
          environment-file: false
          environment-name: mambabuild
          extra-specs: boa
      - name: Build conda package
        shell: bash -l {0}
        run: ./.github/workflows/macos-conda-build.sh

  windows-conda-build:
    if: false
    name: "Windows - conda-build - ${{ matrix.CONDA_BUILD_YML }}"
    runs-on: windows-2019
    env:
      CI: True
      CONDA_BUILD_YML: "${{ matrix.CONDA_BUILD_YML }}"
    strategy:
      fail-fast: false
      matrix:
        CONDA_BUILD_YML:
          - win_64_
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Fetch full git history
        run: git fetch --prune --unshallow
      - uses: conda-incubator/setup-miniconda@35d1405e78aa3f784fe3ce9a2eb378d5eeb62169
        with:
          miniforge-variant: Mambaforge
          miniforge-version: 4.10.0-0
          use-mamba: true
#      - name: Debug
#        uses: mxschmitt/action-tmate@v3
      - name: Build conda package
        shell: pwsh
        run: |
          mamba install -n base -y conda-build
          conda build -m .ci_support/${{ matrix.CONDA_BUILD_YML }}.yaml conda.recipe
