name: CI

on:
  push: null
  pull_request: null

jobs:
  test_broken_channels:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
      - shell: bash
        run: |
          x="$(cat docs/environment.yml)"
          echo "$x" | sed s/forge/broken/ > env.yml
          micromamba create -n testenv --strict-channel-priority -y --log-level trace -f env.yml
